// SPDX-License-Identifier: GPL-2.0 OR BSD-3-Clause
#define DILITHIUM_TYPE_87
#include "dilithium.h"

#define DILITHIUM_TYPE			"87"
#define DILITHIUM_MODE			5
#define DILITHIUM_NIST_CATEGORY		DILITHIUM87_NIST_CATEGORY
#define DILITHIUM_LAMBDA		DILITHIUM87_LAMBDA
#define DILITHIUM_K			DILITHIUM87_K
#define DILITHIUM_L			DILITHIUM87_L
#define DILITHIUM_ETA			DILITHIUM87_ETA
#define DILITHIUM_TAU			DILITHIUM87_TAU
#define DILITHIUM_BETA			DILITHIUM87_BETA
#define DILITHIUM_GAMMA1		DILITHIUM87_GAMMA1
#define DILITHIUM_GAMMA2		DILITHIUM87_GAMMA2
#define DILITHIUM_OMEGA			DILITHIUM87_OMEGA

#define DILITHIUM_CTILDE_BYTES		DILITHIUM87_CTILDE_BYTES
#define DILITHIUM_POLYT1_PACKEDBYTES	DILITHIUM87_POLYT1_PACKEDBYTES
#define DILITHIUM_POLYT0_PACKEDBYTES	DILITHIUM87_POLYT0_PACKEDBYTES
#define DILITHIUM_POLYVECH_PACKEDBYTES	DILITHIUM87_POLYVECH_PACKEDBYTES
#define DILITHIUM_POLYZ_PACKEDBYTES	DILITHIUM87_POLYZ_PACKEDBYTES
#define DILITHIUM_POLYW1_PACKEDBYTES	DILITHIUM87_POLYW1_PACKEDBYTES
#define DILITHIUM_POLYETA_PACKEDBYTES	DILITHIUM87_POLYETA_PACKEDBYTES

#define DILITHIUM_PUBLICKEYBYTES	DILITHIUM87_PUBLICKEYBYTES
#define DILITHIUM_SECRETKEYBYTES	DILITHIUM87_SECRETKEYBYTES
#define DILITHIUM_CRYPTO_BYTES		DILITHIUM87_CRYPTO_BYTES

#include "dilithium_ntt.c"
#include "dilithium_poly.c"
#include "dilithium_rounding.c"
#include "dilithium_signature_c.c"
