// SPDX-License-Identifier: GPL-2.0 OR BSD-3-Clause
#define DILITHIUM_TYPE_44
#include "dilithium.h"

#define DILITHIUM_TYPE			"44"
#define DILITHIUM_MODE			2
#define DILITHIUM_NIST_CATEGORY		DILITHIUM44_NIST_CATEGORY
#define DILITHIUM_LAMBDA		DILITHIUM44_LAMBDA
#define DILITHIUM_K			DILITHIUM44_K
#define DILITHIUM_L			DILITHIUM44_L
#define DILITHIUM_ETA			DILITHIUM44_ETA
#define DILITHIUM_TAU			DILITHIUM44_TAU
#define DILITHIUM_BETA			DILITHIUM44_BETA
#define DILITHIUM_GAMMA1		DILITHIUM44_GAMMA1
#define DILITHIUM_GAMMA2		DILITHIUM44_GAMMA2
#define DILITHIUM_OMEGA			DILITHIUM44_OMEGA

#define DILITHIUM_CTILDE_BYTES		DILITHIUM44_CTILDE_BYTES
#define DILITHIUM_POLYT1_PACKEDBYTES	DILITHIUM44_POLYT1_PACKEDBYTES
#define DILITHIUM_POLYT0_PACKEDBYTES	DILITHIUM44_POLYT0_PACKEDBYTES
#define DILITHIUM_POLYVECH_PACKEDBYTES	DILITHIUM44_POLYVECH_PACKEDBYTES
#define DILITHIUM_POLYZ_PACKEDBYTES	DILITHIUM44_POLYZ_PACKEDBYTES
#define DILITHIUM_POLYW1_PACKEDBYTES	DILITHIUM44_POLYW1_PACKEDBYTES
#define DILITHIUM_POLYETA_PACKEDBYTES	DILITHIUM44_POLYETA_PACKEDBYTES

#define DILITHIUM_PUBLICKEYBYTES	DILITHIUM44_PUBLICKEYBYTES
#define DILITHIUM_SECRETKEYBYTES	DILITHIUM44_SECRETKEYBYTES
#define DILITHIUM_CRYPTO_BYTES		DILITHIUM44_CRYPTO_BYTES

#include "dilithium_ntt.c"
#include "dilithium_poly.c"
#include "dilithium_rounding.c"
#include "dilithium_signature_c.c"
