// SPDX-License-Identifier: GPL-2.0 OR BSD-3-Clause
#define DILITHIUM_TYPE_65
#include "dilithium.h"

#define DILITHIUM_TYPE			"65"
#define DILITHIUM_MODE			3
#define DILITHIUM_NIST_CATEGORY		DILITHIUM65_NIST_CATEGORY
#define DILITHIUM_LAMBDA		DILITHIUM65_LAMBDA
#define DILITHIUM_K			DILITHIUM65_K
#define DILITHIUM_L			DILITHIUM65_L
#define DILITHIUM_ETA			DILITHIUM65_ETA
#define DILITHIUM_TAU			DILITHIUM65_TAU
#define DILITHIUM_BETA			DILITHIUM65_BETA
#define DILITHIUM_GAMMA1		DILITHIUM65_GAMMA1
#define DILITHIUM_GAMMA2		DILITHIUM65_GAMMA2
#define DILITHIUM_OMEGA			DILITHIUM65_OMEGA

#define DILITHIUM_CTILDE_BYTES		DILITHIUM65_CTILDE_BYTES
#define DILITHIUM_POLYT1_PACKEDBYTES	DILITHIUM65_POLYT1_PACKEDBYTES
#define DILITHIUM_POLYT0_PACKEDBYTES	DILITHIUM65_POLYT0_PACKEDBYTES
#define DILITHIUM_POLYVECH_PACKEDBYTES	DILITHIUM65_POLYVECH_PACKEDBYTES
#define DILITHIUM_POLYZ_PACKEDBYTES	DILITHIUM65_POLYZ_PACKEDBYTES
#define DILITHIUM_POLYW1_PACKEDBYTES	DILITHIUM65_POLYW1_PACKEDBYTES
#define DILITHIUM_POLYETA_PACKEDBYTES	DILITHIUM65_POLYETA_PACKEDBYTES

#define DILITHIUM_PUBLICKEYBYTES	DILITHIUM65_PUBLICKEYBYTES
#define DILITHIUM_SECRETKEYBYTES	DILITHIUM65_SECRETKEYBYTES
#define DILITHIUM_CRYPTO_BYTES		DILITHIUM65_CRYPTO_BYTES

#include "dilithium_ntt.c"
#include "dilithium_poly.c"
#include "dilithium_rounding.c"
#include "dilithium_signature_c.c"
