# SPDX-License-Identifier: GPL-2.0
---
name: Run kdevops CI Workflow - Manual

on:
  workflow_dispatch:
    inputs:
      ci_workflow:
        description: "CI Workflow"
        required: true
        default: 'blktests_nvme'
        type: choice
        options:
          - blktests
          - blktests_block
          - blktests_loop
          - blktests_meta
          - blktests_nbd
          - blktests_nvme
          - blktests_nvmemp
          - blktests_scsi
          - blktests_srp
          - blktests_zbd
          - tmpfs
          - tmpfs_default
          - tmpfs_huge
          - tmpfs_noswap
          - linux-btrfs-kpd
          - linux-ext4-kpd
          - linux-firmware-kpd
          - linux-mm-kpd
          - linux-modules-kpd
          - linux-xfs-kpd
          - selftests
      kernel_tree:
        description: "Linux kernel tree to use"
        required: true
        default: 'linux'
        type: choice
        options:
          - linux
          - linux-next
          - linux-stable
      kernel_ref:
        description: "Linux tree git reference (branch/tag/commit-id)"
        required: true
        default: 'master'
        type: string

jobs:
  manual:
    name: Manual kdevops CI
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      ci_workflow: ${{ inputs.ci_workflow }}
      kernel_ref: ${{ inputs.kernel_ref }}
      kernel_tree: ${{ inputs.kernel_tree }}
